on:
  push:
    branches: [ angga ]

jobs:
  build:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dubnium
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        ports:
          - 9000:9000
        options: --name minio-server
      nats:
        image: nats
        ports:
          - 4222:4222

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tugas
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: npm i
    - run: npm run test:worker